version: 1
update_configs:
  - package_manager: 'docker'
    directory: '/docker/node/security-patch'
    update_schedule: 'daily'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'security:patch'
  - package_manager: 'docker'          
    directory: '/docker/node/semver-patch'
    update_schedule: 'daily'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'semver:patch'        
  - package_manager: 'docker'          
    directory: '/docker/node/semver-minor'
    update_schedule: 'daily'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'semver:minor'  
  - package_manager: 'docker'          
    directory: '/docker/node/default'
    update_schedule: 'daily'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'semver:minor'                 
